
"""
    wrspice_input_paramp(netlist, ws, wp, Ip, sourcenodes, sourcenodep;
        stepsperperiod = 80, Is = 1e-13, tstop = 200e-9, trise = 10e-9,
        dphimax = 0.01, maxdata = 2e9)

Generate the WRSPICE inputs for the time domain simulations of a
parametric amplifier: one with the pump alone at angular frequency `wp`
and current `Ip`, applied between the `(src, dst)` node pair
`sourcenodep`, and then for each signal angular frequency in `ws` one with
a small sine and one with a small cosine signal of amplitude `Is` added
between the node pair `sourcenodes`. A source draws its current from `src`
and injects it into `dst`, as SPICE orients a current source, so a drive
into port node `1` is `(0, 1)`. Returns the vector of input strings, pump
first, which [`spice_run`](@ref) runs and [`wrspice_calcS_paramp`](@ref)
turns into scattering parameters. `stepsperperiod` time steps per pump
period are taken for `tstop` seconds with a rise time `trise` (see
[`wrspice_input_transient`](@ref)).

# Examples
```
using JosephsonCircuits
using Plots
circuit = Circuit(
    [:p1 => Port(1; Z0 = :R),
     :cc => Capacitor(:Cc),
     :jj => JosephsonJunction(:Lj),
     :cj => Capacitor(:Cj),
     :gnd => Ground()],
    [Net("1", [(:p1, 1), (:cc, 1)]),
     Net("2", [(:cc, 2), (:jj, 1), (:cj, 1)]),
     Net("0", [(:p1, 2), (:jj, 2), (:cj, 2), (:gnd, 1)])])
circuitdefs = Dict(
    :Lj =>1000.0e-12,
    :Cc => 100.0e-15,
    :Cj => 1000.0e-15,
    :R => 50.0)
ws = 2*pi*(4.5:0.001:5.0)*1e9
wp = (2*pi*4.75001*1e9,)
Ip = 0.00565e-6
sources = [(mode=(1,),port=1,current=Ip)]
Npumpharmonics = (16,)
Nmodulationharmonics = (8,)
@time jpa = hbsolve(ws, wp, sources, Nmodulationharmonics,
    Npumpharmonics, circuit, circuitdefs)
wswrspice=2*pi*(4.5:0.01:5.0)*1e9
n = JosephsonCircuits.exportnetlist(circuit,circuitdefs);
input = JosephsonCircuits.wrspice_input_paramp(n.netlist,wswrspice,wp[1],2*Ip,(0,1),(0,1));
@time output = JosephsonCircuits.spice_run(input,JosephsonCircuits.wrspice_cmd());
S11,S21=JosephsonCircuits.wrspice_calcS_paramp(output,wswrspice,n.Nnodes);
plot(ws/(2*pi*1e9),
    10*log10.(abs2.(jpa.linearized.S((0,),1,(0,),1,:))),
    label="JosephsonCircuits.jl",
    xlabel="Frequency (GHz)",
    ylabel="S11 (dB)")
plot!(wswrspice/(2*pi*1e9),10*log10.(abs2.(S11)),
    label="WRSPICE",
    seriestype=:scatter)
```
"""
function wrspice_input_paramp(netlist, ws, wp, Ip, sourcenodes,sourcenodep;
    stepsperperiod = 80, Is = 1e-13, tstop = 200e-9, trise = 10e-9,
    dphimax = 0.01, maxdata = 2e9)

    # the pump frequency in Hz
    fp = wp/(2*pi)

    # the time step
    tstep = 1/(maximum(fp)*stepsperperiod)

    # combine the source nodes into a vector
    sourcenode = vcat(sourcenodep,sourcenodes)

    # the pump only simulation
    inputpump = wrspice_input_transient(netlist, Ip, fp, zeros(length(Ip)), sourcenodep,
            tstep, tstop, trise; dphimax = dphimax, maxdata = maxdata);
    input = [inputpump]

    for i = 1:length(ws)
        fs = ws[i]/(2*pi)

        inputsin = wrspice_input_transient(netlist, vcat(Ip,Is), vcat(fp,fs),
            vcat(zeros(length(Ip)), -pi/2), sourcenode,
            tstep, tstop, trise; dphimax = dphimax, maxdata = maxdata);
        push!(input,inputsin)

        inputcos = wrspice_input_transient(netlist, vcat(Ip,Is), vcat(fp,fs),
            vcat(zeros(length(Ip)), 0.0), sourcenode,
            tstep, tstop, trise; dphimax = dphimax, maxdata = maxdata);
        push!(input,inputcos)
    end

    return input

end

"""
    wrspice_calcS_paramp(out, wswrspice, Nnodes; stepsperperiod = 80,
        Is = 1e-13)

The reflection `S11` and transmission `S21` of a parametric amplifier at
the signal angular frequencies `wswrspice`, from the WRSPICE outputs `out`
of the simulations generated by [`wrspice_input_paramp`](@ref) with the
same `stepsperperiod` and `Is`. The traces `v(1)` and `v(Nnodes-1)`,
found by name, are taken as the input and the output port, both of 50
ohms, where `Nnodes` is the number of nodes including ground; so the
nets must be named by the integers `0` to `Nnodes-1`, and an output
without either trace is an error. The signal response at a node is the
difference of its voltage with the signal and without it, the cosine
and the sine responses combined as the real and imaginary parts of one
complex response, demodulated at the signal frequency and averaged over
the last pump period, over which the mixing products, the idlers
included, average to zero. The incident wave of the signal source is
half its Thevenin voltage `50*Is`.

# Examples
```jldoctest
# the voltages of a port which reflects S11 = 0.5*cis(pi/3) at the signal
# frequency, on the last pump period, with the pump's own response
ws = 2*pi*5e9
wp = 2*pi*6e9
stepsperperiod = 80
Is = 1e-13
t = collect(0:stepsperperiod - 1)*2*pi/(wp*stepsperperiod)
V = (1 + 0.5*cis(pi/3))*50*Is/2
Vpump = reshape(1e-6*cos.(wp*t), 1, :)
Vcos = Vpump .+ reshape(real.(V*cis.(ws*t)), 1, :)
Vsin = Vpump .+ reshape(real.(-im*V*cis.(ws*t)), 1, :)
variables = Dict("V" => ["v(1)"])
out = [(variables = variables, values = Dict("S" => t, "V" => Vpump)),
    (variables = variables, values = Dict("S" => t, "V" => Vsin)),
    (variables = variables, values = Dict("S" => t, "V" => Vcos))]
S = JosephsonCircuits.wrspice_calcS_paramp(out, [ws], 2;
    stepsperperiod = stepsperperiod, Is = Is)
abs(only(S.S11) - 0.5*cis(pi/3)) < 1e-10

# output
true
```
"""
function wrspice_calcS_paramp(out, wswrspice, Nnodes; stepsperperiod = 80,
    Is = 1e-13)

    if length(out) != length(wswrspice)*2+1
        error(lazy"Number of WRspice simulations not consistent with number of frequencies.")
    end

    # empty arrays for the scattering parameters
    S11 = zeros(Complex{Float64},length(wswrspice))
    S21 = zeros(Complex{Float64},length(wswrspice))

    # the Thevenin voltage of the signal source, twice the incident wave
    Vth = Is*50

    for i = 1:length(wswrspice)

        # the signal response at node `node`, demodulated at the signal
        # frequency and averaged over the last pump period
        function response(node)
            pump, withsin, withcos = out[1], out[2*i], out[2*i+1]
            vpump = pump.values["V"]
            vsin = withsin.values["V"]
            vcos = withcos.values["V"]
            rp = wrspicenoderow(pump, node)
            rs = wrspicenoderow(withsin, node)
            rc = wrspicenoderow(withcos, node)
            t = pump.values["S"]
            n = size(vpump, 2)
            v = zero(Complex{Float64})
            for j = n-stepsperperiod+1:n
                v += complex(vcos[rc,j] - vpump[rp,j], vsin[rs,j] - vpump[rp,j])*
                    cis(-wswrspice[i]*t[j])
            end
            return v/stepsperperiod
        end

        S11[i] = (2*response(1) - Vth)/Vth
        S21[i] = 2*response(Nnodes-1)/Vth

    end
    return (S11=S11,S21=S21)
end

# the row of the voltage trace of node `node` in a WRSPICE output, found by
# name, as the rawfile names it: v(node)
function wrspicenoderow(out, node)
    key = "v($(node))"
    traces = out.variables["V"]
    row = findfirst(name -> lowercase(name) == key, traces)
    if isnothing(row)
        held = join(traces, ", ")
        throw(ArgumentError(lazy"the WRSPICE output has no trace $(key); it holds $(held). The nets must be named by the integers 0 to Nnodes-1."))
    end
    return row
end
