
"""
    wrspice_input_paramp(netlist, ws, wp, Ip, sourcenodes, sourcenodep;
        stepsperperiod = 80, Is = 1e-13, tstop = 200e-9, trise = 10e-9,
        dphimax = 0.01, maxdata = 2e9)

Generate the WRSPICE inputs for the time domain simulations of a
parametric amplifier: one with the pump alone at angular frequency `wp`
and current `Ip`, applied between the `(src, dst)` node pair
`sourcenodep`, and then for each signal angular frequency in `ws` one with
a small sine and one with a small cosine signal of amplitude `Is` added
between the node pair `sourcenodes`. Returns the vector of input strings, pump first, which
[`spice_run`](@ref) runs and [`wrspice_calcS_paramp`](@ref) turns into
scattering parameters. `stepsperperiod` time steps per pump period are
taken for `tstop` seconds with a rise time `trise` (see
[`wrspice_input_transient`](@ref)).

# Examples
```
using JosephsonCircuits
using Plots
circuit = Circuit(
    [:p1 => Port(1; Z0 = :R),
     :cc => Capacitor(:Cc),
     :jj => JosephsonJunction(:Lj),
     :cj => Capacitor(:Cj),
     :gnd => Ground()],
    [[(:p1, 1), (:cc, 1)],
     [(:cc, 2), (:jj, 1), (:cj, 1)],
     [(:p1, 2), (:jj, 2), (:cj, 2), (:gnd, 1)]])
circuitdefs = Dict(
    :Lj =>1000.0e-12,
    :Cc => 100.0e-15,
    :Cj => 1000.0e-15,
    :R => 50.0)
ws = 2*pi*(4.5:0.001:5.0)*1e9
wp = (2*pi*4.75001*1e9,)
Ip = 0.00565e-6
sources = [(mode=(1,),port=1,current=Ip)]
Npumpharmonics = (16,)
Nmodulationharmonics = (8,)
@time jpa = hbsolve(ws, wp, sources, Nmodulationharmonics,
    Npumpharmonics, circuit, circuitdefs)
wswrspice=2*pi*(4.5:0.01:5.0)*1e9
n = JosephsonCircuits.exportnetlist(circuit,circuitdefs);
input = JosephsonCircuits.wrspice_input_paramp(n.netlist,wswrspice,wp[1],2*Ip,(1,0),(1,0));
@time output = JosephsonCircuits.spice_run(input,JosephsonCircuits.wrspice_cmd());
S11,S21=JosephsonCircuits.wrspice_calcS_paramp(output,wswrspice,n.Nnodes);
plot(ws/(2*pi*1e9),
    10*log10.(abs2.(jpa.linearized.S((0,),1,(0,),1,:))),
    label="JosephsonCircuits.jl",
    xlabel="Frequency (GHz)",
    ylabel="S11 (dB)")
plot!(wswrspice/(2*pi*1e9),10*log10.(abs2.(S11)),
    label="WRSPICE",
    seriestype=:scatter)
```
"""
function wrspice_input_paramp(netlist, ws, wp, Ip, sourcenodes,sourcenodep;
    stepsperperiod = 80, Is = 1e-13, tstop = 200e-9, trise = 10e-9,
    dphimax = 0.01, maxdata = 2e9)

    # the pump frequency in Hz
    fp = wp/(2*pi)

    # the time step
    tstep = 1/(maximum(fp)*stepsperperiod)

    # combine the source nodes into a vector
    sourcenode = vcat(sourcenodep,sourcenodes)

    # the pump only simulation
    inputpump = wrspice_input_transient(netlist, Ip, fp, zeros(length(Ip)), sourcenodep,
            tstep, tstop, trise; dphimax = dphimax, maxdata = maxdata);
    input = [inputpump]

    for i = 1:length(ws)
        fs = ws[i]/(2*pi)

        inputsin = wrspice_input_transient(netlist, vcat(Ip,Is), vcat(fp,fs),
            vcat(zeros(length(Ip)), -pi/2), sourcenode,
            tstep, tstop, trise; dphimax = dphimax, maxdata = maxdata);
        push!(input,inputsin)

        inputcos = wrspice_input_transient(netlist, vcat(Ip,Is), vcat(fp,fs),
            vcat(zeros(length(Ip)), 0.0), sourcenode,
            tstep, tstop, trise; dphimax = dphimax, maxdata = maxdata);
        push!(input,inputcos)
    end

    return input

end

"""
    wrspice_calcS_paramp(out, wswrspice, Nnodes; stepsperperiod = 80,
        Is = 1e-13)

The reflection `S11` and transmission `S21` of a parametric amplifier at
the signal angular frequencies `wswrspice`, from the WRSPICE outputs `out`
of the simulations generated by [`wrspice_input_paramp`](@ref) with the
same `stepsperperiod` and `Is`. The first node is taken as the input port
and the last node as the output port; `Nnodes` is the number of nodes
including ground.

# Examples
```jldoctest
Nnodes = 2
ws = 2*pi*5e9
wp = 2*pi*6e9
stepsperperiod = 80
t = LinRange(0,2*pi/wp,stepsperperiod)
Is = 1e-13
Vpump = zeros(1,length(t))
Vsignalsin = zeros(1,length(t))
Vsignalcos = zeros(1,length(t))
Vpump[1,:] .= sin.(2*pi*wp*t)
Vsignalsin[1,:] .= sin.(2*pi*wp*t)+Is/50*sin.(2*pi*ws*t)
Vsignalcos[1,:] .= sin.(2*pi*wp*t)+Is/50*cos.(2*pi*ws*t)

out = [(values=Dict("S"=>t,"V"=>Vpump),),
        (values=Dict("S"=>t,"V"=>Vsignalsin),),
        (values=Dict("S"=>t,"V"=>Vsignalcos),),
        ];
out[1].values["V"];
out[2].values["V"];
out[3].values["V"];
JosephsonCircuits.wrspice_calcS_paramp(out, 2*pi, Nnodes;
    stepsperperiod = stepsperperiod, Is = Is)

# output
(S11 = ComplexF64[-0.9999710828404902 + 2.7521387922213123e-5im], S21 = ComplexF64[2.8917159509832197e-5 + 2.7521387922213123e-5im])
```
"""
function wrspice_calcS_paramp(out, wswrspice, Nnodes; stepsperperiod = 80,
    Is = 1e-13)

    if length(out) != length(wswrspice)*2+1
        error(lazy"Number of WRspice simulations not consistent with number of frequencies.")
    end

    # empty arrays for the scattering parameters
    S11 = zeros(Complex{Float64},length(wswrspice))
    S21 = zeros(Complex{Float64},length(wswrspice))

    for i = 1:length(wswrspice)

        vpump = out[1].values["V"][1:Nnodes-1,end-stepsperperiod+1:end]
        vsinpump = out[2*i].values["V"][1:Nnodes-1,end-stepsperperiod+1:end]
        vcospump = out[2*i+1].values["V"][1:Nnodes-1,end-stepsperperiod+1:end]
        vsin = vsinpump .- vpump
        vcos = vcospump .- vpump

        t = out[1].values["S"][end-stepsperperiod+1:end]

        # the complex signal response, demodulated at the signal frequency
        # and Fourier transformed over the last pump period
        vsincos = vcos .+ im*vsin
        for k = 1:Nnodes-1
            for j = 1:stepsperperiod
                vsincos[k,j] = vsincos[k,j]*exp.(-im*wswrspice[i]*t[j])
            end
        end

        ftvsincos = FFTW.fft(vsincos,[2])/stepsperperiod;

        # S11 and S21 from the demodulated voltages at the first and last
        # nodes, driven from a Thevenin source of 50 ohms
        Vth=Is*50

        V1=ftvsincos[1,1]
        V2=ftvsincos[end,1]

        S11[i] =(2 .* V1 .- Vth) ./ Vth
        S21[i] = 2*V2 ./ Vth .* sqrt(50/50)

    end
    return (S11=S11,S21=S21)
end

